config/routes.rb
Treebook::Application.routes.draw do
  devise_for :users
  resources :statuses

  root to: 'statuses#index'
  devise_scope :user do
    get '/signout' => 'devise/sessions#destroy'
  end

end

app/models/status.rb
class Status < ActiveRecord::Base
	
	belongs_to :user
	
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :statuses

  def full_name
    first_name + " " + last_name
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/statuses_controller.rb
class StatusesController < ApplicationController
  before_filter :authenticate_user!, only: [:create, :update, :new, :edit]
  before_action :set_status, only: [:show, :edit, :update, :destroy]

  # GET /statuses
  # GET /statuses.json
  def index
    @statuses = Status.all
  end

  # GET /statuses/1
  # GET /statuses/1.json
  def show
  end

  # GET /statuses/new
  def new
    @status = Status.new
  end

  # GET /statuses/1/edit
  def edit
  end

  # POST /statuses
  # POST /statuses.json
  def create
    @status = current_user.statuses.new(status_params)

    respond_to do |format|
      if @status.save
        format.html { redirect_to @status, notice: 'Status was successfully created.' }
        format.json { render action: 'show', status: :created, location: @status }
      else
        format.html { render action: 'new' }
        format.json { render json: @status.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /statuses/1
  # PATCH/PUT /statuses/1.json
  def update
    respond_to do |format|
      if @status.update(status_params)
        format.html { redirect_to @status, notice: 'Status was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @status.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /statuses/1
  # DELETE /statuses/1.json
  def destroy
    @status.destroy
    respond_to do |format|
      format.html { redirect_to statuses_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_status
      @status = Status.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def status_params
      params.require(:status).permit(:name, :content)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/statuses_helper.rb
module StatusesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Treebook</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
	<div class="navbar navbar-fixed-top">
	  <div class="navbar-inner">
	    <a class="brand" href="#">Treebook</a>
	    <ul class="nav">
	      <li class="active"><a href="#">Home</a></li>
	      <li><%= link_to "All Statuses", statuses_path %></li>
	      <li><a href="#">Link</a></li>
	    </ul>
	  </div>
	</div> 
	<div class = "container">
		<%= yield %>
	</div>

</body>
</html>

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title Treebook
    = stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true
    = javascript_include_tag "application", "data-turbolinks-track" => true
    = csrf_meta_tags
  %body
    .navbar.navbar-fixed-top
      .navbar-inner
        %a.brand{:href => "#"} Treebook
        %ul.nav
          %li.active
            %a{:href => "#"} Home
          %li= link_to "All Statuses", statuses_path
          %li
            %a{:href => "#"} Link
    .container
      %p.notice= notice
      %p.alert= alert
      = yield

app/views/statuses/_form.html.haml
= simple_form_for(@status, html: {class: "form-horizontal"}) do |f|
  - if @status.errors.any?
    #error_explanation
      %h2
        = pluralize(@status.errors.count, "error")
        prohibited this status from being saved:
      %ul
        - @status.errors.full_messages.each do |msg|
          %li= msg
  
  = f.input :user_id, collection:        
  = f.input :content

  .form-actions
    = f.button :submit

app/views/statuses/edit.html.haml
%h1 Editing status
= render 'form'
= link_to 'Show', @status
|
#{link_to 'Back', statuses_path}

app/views/statuses/index.html.haml
.page-header
  %h1 All of the Statuses
= link_to "Post a New Status", new_status_path, class: "btn btn-success"
- @statuses.each do |status|
  .status
    %strong= status.user.full_name
    %p= status.content
    .meta
      = link_to time_ago_in_words(status.created_at) + " ago", status
      %span.admin
        | #{link_to "Edit", edit_status_path(status)} |
        #{link_to "Destroy", status, method: :delete, data: { confirm: "Are you sure you want to delete this status?"}}

app/views/statuses/new.html.haml
%h1 New status

= render 'form'

= link_to 'Back', statuses_path

app/views/statuses/show.html.haml
%p #notice = notice

%p
	%strong Name:
	= @status.user.full_name
%p
	%strong Content:
	= @status.content

= link_to 'Edit', edit_status_path(@status) |
= link_to 'Back', statuses_path